CREATE TABLE VERSION (
  ID INT AUTO_INCREMENT,
  COMMAND VARCHAR(64),
  NAME VARCHAR(256),
  VERSION VARCHAR(512),
  DOWNLOAD_URL VARCHAR(1024),
  RELEASE_NOTES_URL VARCHAR(1024),
  LAST_UPDATE TIMESTAMP,
  WAS_REPORTED BOOLEAN
);
